services:
  redis:
    image: redis:8
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - inventoryservice_default

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8181:8181'
    networks:
      - inventoryservice_default

networks:
  inventoryservice_default:
    external: true